### ISSUE TITLE
Secret cannot handle multiple arguments

### ISSUE THREAD

**Issue by skippy** [hashicorp/consul-template#678]
The secret example, https://github.com/hashicorp/consul-template#secret, shows:

```liquid
{{ secret "path/" "a=b", "c=d", "e=f" }}
```
as a valid example, but that seems to fail with a `pki` call.  This may be similar to #660 ?

### Template - FAILING
```liquid
{{ with secret "pki/issue/base" "common_name=internal-proxy.service.consul", "format=pem_bundle" }}
{{ .Data.certificate }}
{{ end }}
```

### Failing Output

`template: template: pem.tmpl:1: unexpected "," in operand`

### Template - WORKS
```liquid
{{ with secret "pki/internal-services/issue/base" "common_name=internal-proxy.service.consul" }}
{{ .Data.private_key}}
{{ .Data.certificate }}
{{ .Data.issuing_ca }}
{{ end }}
```

**Comment by sethvargo** [comment]
Already fixed in master https://github.com/hashicorp/consul-template/pull/662

**Comment by skippy** [comment]
hi @sethvargo 

this was with
```shell
$ consul-template -v
consul-template v0.16.0rc1 (44afc882e6c25fe4d62654999f826d68271ff807+CHANGES)
```

so it looks like it still exists.

**Comment by sethvargo** [comment]
That example is just wrong: https://github.com/hashicorp/consul-template/commit/ae7d6e86a41ab9968388593bc2a36f5107828dae

**Comment by skippy** [comment]
AH!!!  Damn, I tried a few combinations but not that one... thanks for the update!
